library(sqldf)
powercons <- file("household_power_consumption.txt")
attr(powercons,"file.format") <- list(sep=";",header=TRUE)
powercons_df <- sqldf("Select * from powercons where Date ='1/2/2007' OR Date='2/2/2007'")
powercons_df$DateTime <- paste(powercons_df$Date,powercons_df$Time)
powercons_df$DateTime <- strptime(powercons_df$DateTime, format = "%d/%m/%Y %H:%M:%S")
png(file="plot2.png",width = 480, height = 480,bg="transparent")
par(mfrow=c(1,1))
plot(powercons_df$DateTime,powercons_df$Global_active_power, type="n",ylab="Global Active Power (killowatts)", xlab= "")
lines(powercons_df$DateTime,powercons_df$Global_active_power)
dev.off()
