library(sqldf)
powercons <- file("household_power_consumption.txt")
attr(powercons,"file.format") <- list(sep=";",header=TRUE)
powercons_df <- sqldf("Select * from powercons where Date ='1/2/2007' OR Date='2/2/2007'")
powercons_df$DateTime <- paste(powercons_df$Date,powercons_df$Time)
powercons_df$DateTime <- strptime(powercons_df$DateTime, format = "%d/%m/%Y %H:%M:%S")
png(file="plot3.png",width = 480, height = 480,bg="transparent")
par(mfrow=c(1,1))
plot(powercons_df$DateTime,powercons_df$Sub_metering_1, ylab="Energy sub metering", type = "n", xlab= "")
lines(powercons_df$DateTime,powercons_df$Sub_metering_1,col="BLACK")
lines(powercons_df$DateTime,powercons_df$Sub_metering_2,col="RED")
lines(powercons_df$DateTime,powercons_df$Sub_metering_3,col="BLUE")
legend("topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=c(1,1,1),,lwd=c(2.5,2.5,2.5),col=c("black","red","blue"))
dev.off()